// Offline differential diagnosis database. No external calls.
// Curated for Cameroon clinic context. Minimum 5–8 conditions per system.

export type Confidence = "high" | "medium" | "low";

export interface Disease {
  name: string;
  /** Symptoms that increase the score */
  symptoms: string[];
  description: string;
  keyFeatures: string;
  investigations: string;
  redFlags: string;
  /** Modifiers used by the ranker */
  durations?: ("acute" | "subacute" | "chronic")[];
  severities?: ("mild" | "moderate" | "severe")[];
}

export interface BodySystem {
  id: string;
  /** English name */
  nameEn: string;
  /** French name */
  nameFr: string;
  symptoms: string[]; // canonical pool for this system (English keys)
  diseases: Disease[];
}

export const SYSTEMS: BodySystem[] = [
  {
    id: "general",
    nameEn: "General & Infectious",
    nameFr: "Général & Infectieux",
    symptoms: [
      "fever", "chills", "sweats", "headache", "fatigue", "myalgia",
      "nausea", "vomiting", "diarrhea", "abdominal_pain", "jaundice",
      "rash", "weight_loss", "lymphadenopathy", "cough",
    ],
    diseases: [
      { name: "Malaria", symptoms: ["fever","chills","sweats","headache","myalgia","fatigue","nausea","vomiting"],
        description: "Plasmodium infection, endemic in Cameroon. Cyclical fevers and rigors are classic.",
        keyFeatures: "Periodic fever, splenomegaly, anemia. Recent travel/residence in endemic area.",
        investigations: "Thick & thin blood smear, RDT (HRP-2), CBC, LFTs.",
        redFlags: "Altered consciousness, seizures, severe anemia, jaundice, hypoglycemia → cerebral/severe malaria.",
        durations: ["acute","subacute"], severities: ["mild","moderate","severe"] },
      { name: "Typhoid Fever", symptoms: ["fever","headache","abdominal_pain","diarrhea","nausea","fatigue","rash"],
        description: "Salmonella Typhi. Stepwise fever rising over a week with relative bradycardia.",
        keyFeatures: "Rose spots, hepatosplenomegaly, constipation early then diarrhea.",
        investigations: "Blood culture (gold standard), Widal test, stool culture, CBC.",
        redFlags: "GI bleed, perforation, altered mental status.",
        durations: ["subacute","chronic"], severities: ["moderate","severe"] },
      { name: "Dengue Fever", symptoms: ["fever","headache","myalgia","rash","nausea","vomiting"],
        description: "Mosquito-borne flavivirus. Sudden high fever with retro-orbital pain.",
        keyFeatures: "Severe myalgia/arthralgia ('breakbone'), petechial rash, leukopenia.",
        investigations: "NS1 antigen, IgM/IgG, CBC (thrombocytopenia), HCT.",
        redFlags: "Bleeding, plasma leakage, shock → dengue hemorrhagic fever.",
        durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Yellow Fever", symptoms: ["fever","jaundice","headache","myalgia","nausea","vomiting"],
        description: "Flavivirus with biphasic illness. Jaundice and hemorrhage in toxic phase.",
        keyFeatures: "Faget's sign (relative bradycardia with high fever), hepatic dysfunction.",
        investigations: "Serology (IgM), PCR, LFTs, coagulation profile.",
        redFlags: "Hematemesis, oliguria, encephalopathy.",
        durations: ["acute"], severities: ["severe"] },
      { name: "Cholera", symptoms: ["diarrhea","vomiting","abdominal_pain","fatigue"],
        description: "Vibrio cholerae. Profuse rice-water diarrhea with rapid dehydration.",
        keyFeatures: "Painless watery stools, severe volume loss, no fever usually.",
        investigations: "Stool dark-field microscopy, stool culture, electrolytes.",
        redFlags: "Hypovolemic shock, anuria, severe acidosis.",
        durations: ["acute"], severities: ["severe"] },
      { name: "Tuberculosis (Pulmonary)", symptoms: ["cough","fever","weight_loss","sweats","fatigue","lymphadenopathy"],
        description: "Mycobacterium tuberculosis. Chronic cough with constitutional symptoms.",
        keyFeatures: "Night sweats, hemoptysis, contact history, HIV co-infection common.",
        investigations: "Sputum AFB ×3, GeneXpert MTB/RIF, CXR, HIV test.",
        redFlags: "Massive hemoptysis, miliary spread, meningitis.",
        durations: ["chronic"], severities: ["moderate","severe"] },
      { name: "HIV / AIDS opportunistic infection", symptoms: ["fever","weight_loss","fatigue","diarrhea","lymphadenopathy","cough"],
        description: "Immunosuppression with opportunistic infections (PCP, Crypto, TB).",
        keyFeatures: "Oral thrush, persistent diarrhea, generalized lymphadenopathy.",
        investigations: "HIV antibody/antigen, CD4 count, viral load, opportunistic workup.",
        redFlags: "CD4 < 200, neurological signs, severe wasting.",
        durations: ["chronic"], severities: ["moderate","severe"] },
      { name: "Bacterial Meningitis", symptoms: ["fever","headache","vomiting","rash","fatigue"],
        description: "Inflammation of meninges, often N. meningitidis or S. pneumoniae.",
        keyFeatures: "Neck stiffness, photophobia, altered mental status, petechial rash.",
        investigations: "Lumbar puncture (CSF analysis), blood cultures, CT before LP if focal signs.",
        redFlags: "Coma, seizures, shock, purpura fulminans.",
        durations: ["acute"], severities: ["severe"] },
    ],
  },
  {
    id: "respiratory",
    nameEn: "Respiratory",
    nameFr: "Respiratoire",
    symptoms: ["cough","sputum","hemoptysis","dyspnea","wheeze","chest_pain","fever","night_sweats","weight_loss"],
    diseases: [
      { name: "Community-Acquired Pneumonia", symptoms: ["cough","sputum","fever","dyspnea","chest_pain"],
        description: "Acute lower respiratory infection, often pneumococcal.",
        keyFeatures: "Productive cough, focal crackles, bronchial breathing.",
        investigations: "CXR, CBC, sputum gram stain & culture, pulse oximetry.",
        redFlags: "Hypoxia, hypotension, confusion (CURB-65 ≥3).",
        durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Acute Bronchitis", symptoms: ["cough","sputum","fever","wheeze"],
        description: "Self-limited inflammation of bronchi, usually viral.",
        keyFeatures: "Cough lasting 1–3 weeks, no consolidation on exam.",
        investigations: "Clinical diagnosis. CXR if pneumonia suspected.",
        redFlags: "Persistent fever, hypoxia → consider pneumonia.",
        durations: ["acute","subacute"], severities: ["mild","moderate"] },
      { name: "Asthma exacerbation", symptoms: ["wheeze","dyspnea","cough","chest_pain"],
        description: "Reversible bronchoconstriction triggered by allergens/infection.",
        keyFeatures: "Episodic wheeze, prolonged expiration, response to bronchodilator.",
        investigations: "Peak flow, SpO2, ABG if severe, CXR to exclude other causes.",
        redFlags: "Silent chest, exhaustion, SpO2 <92%, altered consciousness.",
        durations: ["acute"], severities: ["mild","moderate","severe"] },
      { name: "COPD exacerbation", symptoms: ["cough","sputum","dyspnea","wheeze"],
        description: "Worsening of chronic obstructive lung disease, often infective.",
        keyFeatures: "Smoker, barrel chest, increased sputum purulence.",
        investigations: "ABG, CXR, sputum culture, ECG.",
        redFlags: "Type II respiratory failure, cor pulmonale.",
        durations: ["chronic"], severities: ["moderate","severe"] },
      { name: "Pulmonary Tuberculosis", symptoms: ["cough","hemoptysis","night_sweats","weight_loss","fever"],
        description: "Chronic mycobacterial lung infection.",
        keyFeatures: "Cough >2 weeks, contact history, apical cavitation.",
        investigations: "Sputum AFB, GeneXpert, CXR, HIV.",
        redFlags: "Massive hemoptysis, miliary TB.",
        durations: ["chronic"], severities: ["moderate","severe"] },
      { name: "Pleural Effusion", symptoms: ["dyspnea","chest_pain","cough","fever"],
        description: "Fluid accumulation in pleural space (TB, parapneumonic, malignant).",
        keyFeatures: "Decreased breath sounds, stony dull percussion, reduced fremitus.",
        investigations: "CXR, ultrasound, diagnostic thoracentesis (Light's criteria).",
        redFlags: "Empyema, large effusion with mediastinal shift.",
        durations: ["subacute","chronic"], severities: ["moderate"] },
      { name: "Pneumothorax", symptoms: ["chest_pain","dyspnea","cough"],
        description: "Air in pleural cavity, sudden onset.",
        keyFeatures: "Sudden pleuritic pain, hyper-resonance, absent breath sounds.",
        investigations: "Erect CXR, US in trauma, CT if uncertain.",
        redFlags: "Tension pneumothorax — needs immediate decompression.",
        durations: ["acute"], severities: ["severe"] },
      { name: "COVID-19", symptoms: ["fever","cough","dyspnea","fatigue"],
        description: "SARS-CoV-2 respiratory infection.",
        keyFeatures: "Anosmia, ageusia, bilateral infiltrates.",
        investigations: "RT-PCR or rapid antigen, SpO2, CXR/CT.",
        redFlags: "SpO2 <94%, ARDS, thromboembolism.",
        durations: ["acute","subacute"], severities: ["mild","moderate","severe"] },
    ],
  },
  {
    id: "cardiovascular", nameEn: "Cardiovascular", nameFr: "Cardiovasculaire",
    symptoms: ["chest_pain","palpitations","dyspnea","syncope","leg_swelling","fatigue","cough","orthopnea"],
    diseases: [
      { name: "Acute Coronary Syndrome", symptoms: ["chest_pain","dyspnea","palpitations","fatigue"],
        description: "Myocardial ischemia from coronary plaque rupture.",
        keyFeatures: "Crushing retrosternal pain radiating to arm/jaw, diaphoresis.",
        investigations: "ECG, troponin, CXR, echo.",
        redFlags: "ST elevation, hypotension, arrhythmias.", durations: ["acute"], severities: ["severe"] },
      { name: "Heart Failure (decompensated)", symptoms: ["dyspnea","orthopnea","leg_swelling","fatigue","cough"],
        description: "Inadequate cardiac output with congestion.",
        keyFeatures: "Bibasal crackles, raised JVP, pitting edema, S3.",
        investigations: "BNP, ECG, CXR, echo.",
        redFlags: "Pulmonary edema, cardiogenic shock.", durations: ["subacute","chronic"], severities: ["moderate","severe"] },
      { name: "Hypertensive Emergency", symptoms: ["headache","chest_pain","dyspnea","palpitations"],
        description: "BP >180/120 with end-organ damage.",
        keyFeatures: "Severe BP, retinal changes, neurological deficits.",
        investigations: "BP both arms, ECG, U&E, urinalysis, fundoscopy.",
        redFlags: "Encephalopathy, aortic dissection, AKI.", durations: ["acute"], severities: ["severe"] },
      { name: "Atrial Fibrillation", symptoms: ["palpitations","dyspnea","fatigue","syncope"],
        description: "Irregular supraventricular arrhythmia.",
        keyFeatures: "Irregularly irregular pulse, no P waves on ECG.",
        investigations: "ECG, TFTs, echo, electrolytes.",
        redFlags: "Hemodynamic instability, stroke (CHA2DS2-VASc).", durations: ["acute","chronic"], severities: ["mild","moderate"] },
      { name: "Pulmonary Embolism", symptoms: ["dyspnea","chest_pain","palpitations","syncope"],
        description: "Thrombus in pulmonary vasculature.",
        keyFeatures: "Sudden dyspnea, pleuritic pain, hypoxia, DVT signs.",
        investigations: "D-dimer, CTPA, ECG (S1Q3T3), ABG.",
        redFlags: "Massive PE → shock, RV strain.", durations: ["acute"], severities: ["severe"] },
      { name: "Rheumatic Heart Disease", symptoms: ["dyspnea","fatigue","palpitations","leg_swelling"],
        description: "Post-streptococcal valvular damage, common in young Africans.",
        keyFeatures: "Mitral stenosis murmur, AF, history of rheumatic fever.",
        investigations: "Echo, ECG, ASO titer.",
        redFlags: "Heart failure, embolic stroke.", durations: ["chronic"], severities: ["moderate"] },
    ],
  },
  {
    id: "gi", nameEn: "Gastrointestinal", nameFr: "Gastro-intestinal",
    symptoms: ["abdominal_pain","nausea","vomiting","diarrhea","constipation","hematemesis","melena","jaundice","weight_loss","fever"],
    diseases: [
      { name: "Acute Gastroenteritis", symptoms: ["diarrhea","vomiting","abdominal_pain","fever","nausea"],
        description: "Viral or bacterial GI infection.",
        keyFeatures: "Watery stools, mild fever, dehydration.",
        investigations: "Stool exam, electrolytes, ORS response.",
        redFlags: "Bloody stools, severe dehydration, oliguria.", durations: ["acute"], severities: ["mild","moderate"] },
      { name: "Peptic Ulcer Disease", symptoms: ["abdominal_pain","nausea","vomiting","hematemesis","melena"],
        description: "Mucosal ulceration, often H. pylori or NSAID-related.",
        keyFeatures: "Epigastric burning, food relation, melena.",
        investigations: "H. pylori stool antigen, endoscopy, FBC.",
        redFlags: "Perforation (peritonitis), massive bleed.", durations: ["chronic"], severities: ["moderate"] },
      { name: "Acute Appendicitis", symptoms: ["abdominal_pain","nausea","vomiting","fever"],
        description: "Inflammation of vermiform appendix.",
        keyFeatures: "Periumbilical → RIF migration, McBurney tenderness, rebound.",
        investigations: "FBC, US, CT abdomen.",
        redFlags: "Perforation, abscess, sepsis.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Amoebiasis", symptoms: ["diarrhea","abdominal_pain","fever","weight_loss"],
        description: "Entamoeba histolytica intestinal/liver infection.",
        keyFeatures: "Bloody mucoid diarrhea, RUQ pain if liver abscess.",
        investigations: "Stool microscopy, US liver, serology.",
        redFlags: "Liver abscess rupture, fulminant colitis.", durations: ["subacute","chronic"], severities: ["moderate"] },
      { name: "Viral Hepatitis", symptoms: ["jaundice","nausea","vomiting","fatigue","abdominal_pain","fever"],
        description: "HAV/HBV/HCV inflammation of liver.",
        keyFeatures: "RUQ tenderness, dark urine, pale stools.",
        investigations: "LFTs, hepatitis serology, INR.",
        redFlags: "Encephalopathy, coagulopathy → fulminant failure.", durations: ["subacute"], severities: ["moderate","severe"] },
      { name: "Intestinal Obstruction", symptoms: ["abdominal_pain","vomiting","constipation","nausea"],
        description: "Mechanical or functional blockage.",
        keyFeatures: "Colicky pain, distension, absolute constipation, tinkling bowel sounds.",
        investigations: "Erect & supine AXR, CT, electrolytes.",
        redFlags: "Strangulation, perforation.", durations: ["acute"], severities: ["severe"] },
    ],
  },
  {
    id: "neuro", nameEn: "Neurological", nameFr: "Neurologique",
    symptoms: ["headache","seizure","weakness","numbness","dizziness","altered_consciousness","visual_change","neck_stiffness","fever"],
    diseases: [
      { name: "Stroke (Ischemic)", symptoms: ["weakness","numbness","altered_consciousness","visual_change","headache"],
        description: "Cerebral infarction from arterial occlusion.",
        keyFeatures: "Sudden focal deficit, FAST positive.",
        investigations: "Non-contrast CT brain urgently, glucose, ECG.",
        redFlags: "Decreased GCS, large MCA, hemorrhagic transformation.", durations: ["acute"], severities: ["severe"] },
      { name: "Migraine", symptoms: ["headache","nausea","visual_change","dizziness"],
        description: "Recurrent unilateral throbbing headache.",
        keyFeatures: "Photophobia, phonophobia, aura, family history.",
        investigations: "Clinical; image if red flags.",
        redFlags: "Sudden 'thunderclap', focal deficit, fever.", durations: ["acute"], severities: ["mild","moderate"] },
      { name: "Bacterial Meningitis", symptoms: ["headache","fever","neck_stiffness","altered_consciousness","seizure"],
        description: "Meningeal infection (N. meningitidis, S. pneumoniae).",
        keyFeatures: "Kernig/Brudzinski, photophobia, petechiae.",
        investigations: "LP after CT if focal signs, blood culture.",
        redFlags: "Coma, shock, purpura.", durations: ["acute"], severities: ["severe"] },
      { name: "Epilepsy / Seizure disorder", symptoms: ["seizure","altered_consciousness","headache"],
        description: "Recurrent unprovoked seizures.",
        keyFeatures: "Tonic-clonic activity, post-ictal confusion, tongue bite.",
        investigations: "EEG, MRI brain, glucose, electrolytes.",
        redFlags: "Status epilepticus >5 min.", durations: ["acute","chronic"], severities: ["moderate","severe"] },
      { name: "Cerebral Malaria", symptoms: ["fever","altered_consciousness","seizure","headache"],
        description: "Severe P. falciparum infection with neurological involvement.",
        keyFeatures: "Coma in endemic area, parasitemia, hypoglycemia.",
        investigations: "Blood film, RDT, glucose, lactate.",
        redFlags: "GCS <11, hypoglycemia, severe acidosis.", durations: ["acute"], severities: ["severe"] },
      { name: "Tension headache", symptoms: ["headache","dizziness"],
        description: "Bilateral pressing headache, common.",
        keyFeatures: "No nausea, mild, related to stress/posture.",
        investigations: "Clinical diagnosis.",
        redFlags: "New pattern, neurological signs.", durations: ["acute","chronic"], severities: ["mild"] },
    ],
  },
  {
    id: "msk", nameEn: "Musculoskeletal", nameFr: "Musculosquelettique",
    symptoms: ["joint_pain","joint_swelling","back_pain","muscle_weakness","stiffness","trauma","fever","rash"],
    diseases: [
      { name: "Osteoarthritis", symptoms: ["joint_pain","stiffness","joint_swelling"],
        description: "Degenerative joint disease.",
        keyFeatures: "Worse with activity, brief morning stiffness, crepitus.",
        investigations: "X-ray (joint space narrowing, osteophytes).",
        redFlags: "Sudden severe pain → consider fracture/septic joint.", durations: ["chronic"], severities: ["mild","moderate"] },
      { name: "Rheumatoid Arthritis", symptoms: ["joint_pain","joint_swelling","stiffness","fatigue"],
        description: "Symmetric autoimmune polyarthritis.",
        keyFeatures: "Morning stiffness >1 hr, MCP/PIP involvement.",
        investigations: "RF, anti-CCP, ESR/CRP, X-rays.",
        redFlags: "Vasculitis, atlantoaxial subluxation.", durations: ["chronic"], severities: ["moderate"] },
      { name: "Septic Arthritis", symptoms: ["joint_pain","joint_swelling","fever","stiffness"],
        description: "Bacterial joint infection — emergency.",
        keyFeatures: "Hot swollen single joint, refusal to move.",
        investigations: "Joint aspiration & culture, CRP, blood culture.",
        redFlags: "Joint destruction, sepsis.", durations: ["acute"], severities: ["severe"] },
      { name: "Gout", symptoms: ["joint_pain","joint_swelling"],
        description: "Monosodium urate crystal arthritis.",
        keyFeatures: "Sudden 1st MTP attack, redness, history of hyperuricemia.",
        investigations: "Joint aspirate (crystals), uric acid.",
        redFlags: "Polyarticular, septic mimic.", durations: ["acute"], severities: ["moderate"] },
      { name: "Mechanical Low Back Pain", symptoms: ["back_pain","stiffness","muscle_weakness"],
        description: "Non-specific musculoskeletal back pain.",
        keyFeatures: "Worse with movement, no neurological deficit.",
        investigations: "Clinical; image only if red flags.",
        redFlags: "Saddle anesthesia, weight loss, fever, bladder dysfunction.", durations: ["acute","chronic"], severities: ["mild","moderate"] },
      { name: "Fracture", symptoms: ["joint_pain","trauma","joint_swelling"],
        description: "Bony discontinuity following trauma.",
        keyFeatures: "Deformity, crepitus, inability to bear weight.",
        investigations: "X-ray two views, CT if complex.",
        redFlags: "Open fracture, neurovascular compromise, compartment syndrome.", durations: ["acute"], severities: ["moderate","severe"] },
    ],
  },
  {
    id: "derm", nameEn: "Dermatology", nameFr: "Dermatologie",
    symptoms: ["rash","pruritus","skin_lesion","fever","blisters","scaling","skin_pain","ulcer"],
    diseases: [
      { name: "Cellulitis", symptoms: ["rash","skin_pain","fever","skin_lesion"],
        description: "Bacterial infection of dermis/subcutaneous tissue.",
        keyFeatures: "Hot, red, tender, poorly demarcated area.",
        investigations: "Clinical, blood culture if systemic.",
        redFlags: "Necrotizing fasciitis, sepsis.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Scabies", symptoms: ["pruritus","rash","skin_lesion"],
        description: "Sarcoptes scabiei mite infestation.",
        keyFeatures: "Nocturnal itch, burrows in web spaces, family contacts.",
        investigations: "Clinical, skin scraping.",
        redFlags: "Crusted (Norwegian) scabies in immunocompromised.", durations: ["subacute","chronic"], severities: ["mild"] },
      { name: "Tinea (fungal infection)", symptoms: ["rash","pruritus","scaling","skin_lesion"],
        description: "Dermatophyte infection.",
        keyFeatures: "Annular scaly plaque with central clearing.",
        investigations: "KOH microscopy.",
        redFlags: "Widespread/immunocompromised host.", durations: ["chronic"], severities: ["mild"] },
      { name: "Eczema (atopic dermatitis)", symptoms: ["pruritus","rash","scaling"],
        description: "Chronic relapsing inflammatory skin condition.",
        keyFeatures: "Flexural distribution, atopic history.",
        investigations: "Clinical.",
        redFlags: "Eczema herpeticum.", durations: ["chronic"], severities: ["mild","moderate"] },
      { name: "Impetigo", symptoms: ["rash","skin_lesion","blisters"],
        description: "Superficial bacterial infection (S. aureus, GAS).",
        keyFeatures: "Honey-colored crusts, perioral.",
        investigations: "Swab if recurrent.",
        redFlags: "Post-strep glomerulonephritis.", durations: ["acute"], severities: ["mild"] },
      { name: "Herpes Zoster (Shingles)", symptoms: ["rash","skin_pain","blisters","fever"],
        description: "Reactivation of varicella-zoster in a dermatome.",
        keyFeatures: "Unilateral vesicular rash, prodromal pain.",
        investigations: "Clinical; PCR if uncertain.",
        redFlags: "Ophthalmic zoster, disseminated disease.", durations: ["acute"], severities: ["moderate"] },
    ],
  },
  {
    id: "ent", nameEn: "ENT", nameFr: "ORL",
    symptoms: ["ear_pain","sore_throat","nasal_congestion","hoarseness","hearing_loss","cough","fever","facial_pain"],
    diseases: [
      { name: "Acute Otitis Media", symptoms: ["ear_pain","fever","hearing_loss"],
        description: "Middle ear infection, common in children.",
        keyFeatures: "Bulging red tympanic membrane, irritability.",
        investigations: "Otoscopy.",
        redFlags: "Mastoiditis, intracranial extension.", durations: ["acute"], severities: ["mild","moderate"] },
      { name: "Streptococcal Pharyngitis", symptoms: ["sore_throat","fever"],
        description: "Group A strep tonsillitis.",
        keyFeatures: "Tonsillar exudate, anterior cervical lymphadenopathy, no cough (Centor).",
        investigations: "Rapid antigen / throat culture.",
        redFlags: "Quinsy, rheumatic fever.", durations: ["acute"], severities: ["mild","moderate"] },
      { name: "Acute Sinusitis", symptoms: ["facial_pain","nasal_congestion","fever","cough"],
        description: "Inflammation of paranasal sinuses.",
        keyFeatures: "Purulent nasal discharge, facial tenderness.",
        investigations: "Clinical; CT if complications.",
        redFlags: "Orbital/intracranial spread.", durations: ["acute","subacute"], severities: ["mild"] },
      { name: "Allergic Rhinitis", symptoms: ["nasal_congestion","cough"],
        description: "IgE-mediated nasal mucosa inflammation.",
        keyFeatures: "Sneezing, clear rhinorrhea, itchy eyes.",
        investigations: "Clinical, allergy testing if needed.",
        redFlags: "Asthma exacerbation.", durations: ["chronic"], severities: ["mild"] },
      { name: "Laryngitis", symptoms: ["hoarseness","cough","sore_throat"],
        description: "Inflammation of larynx.",
        keyFeatures: "Hoarse voice, mostly viral.",
        investigations: "Clinical; laryngoscopy if >3 weeks.",
        redFlags: "Hoarseness >3 weeks → cancer screen.", durations: ["acute","chronic"], severities: ["mild"] },
      { name: "Otitis Externa", symptoms: ["ear_pain","hearing_loss"],
        description: "Outer ear canal infection.",
        keyFeatures: "Pain on tragus pressure, swollen canal.",
        investigations: "Otoscopy, ear swab.",
        redFlags: "Malignant otitis externa in diabetics.", durations: ["acute"], severities: ["mild","moderate"] },
    ],
  },
  {
    id: "uro", nameEn: "Urology & Nephrology", nameFr: "Urologie & Néphrologie",
    symptoms: ["dysuria","frequency","hematuria","flank_pain","fever","urinary_retention","oliguria","leg_swelling"],
    diseases: [
      { name: "Urinary Tract Infection", symptoms: ["dysuria","frequency","hematuria","fever"],
        description: "Bacterial infection of urinary tract.",
        keyFeatures: "Burning urination, urgency, suprapubic pain.",
        investigations: "Urinalysis, urine culture.",
        redFlags: "Pyelonephritis, sepsis.", durations: ["acute"], severities: ["mild","moderate"] },
      { name: "Pyelonephritis", symptoms: ["fever","flank_pain","dysuria","frequency"],
        description: "Upper UTI involving kidney.",
        keyFeatures: "Costovertebral tenderness, high fever, rigors.",
        investigations: "Urine culture, blood culture, US.",
        redFlags: "Sepsis, abscess, obstruction.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Renal Calculi (Stone)", symptoms: ["flank_pain","hematuria","urinary_retention"],
        description: "Crystallized minerals in urinary tract.",
        keyFeatures: "Colicky loin-to-groin pain, restless patient.",
        investigations: "Non-contrast CT KUB, urinalysis.",
        redFlags: "Obstruction with infection — emergency.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Acute Kidney Injury", symptoms: ["oliguria","leg_swelling","fatigue"],
        description: "Sudden decline in renal function.",
        keyFeatures: "Reduced urine output, edema, raised creatinine.",
        investigations: "U&E, creatinine, urinalysis, US.",
        redFlags: "Hyperkalemia, severe acidosis, fluid overload.", durations: ["acute"], severities: ["severe"] },
      { name: "Benign Prostatic Hyperplasia", symptoms: ["frequency","urinary_retention","dysuria"],
        description: "Non-cancerous prostate enlargement.",
        keyFeatures: "Hesitancy, weak stream, nocturia in older men.",
        investigations: "DRE, PSA, US, uroflowmetry.",
        redFlags: "Acute retention, hydronephrosis.", durations: ["chronic"], severities: ["mild","moderate"] },
      { name: "Schistosomiasis (urinary)", symptoms: ["hematuria","dysuria","frequency"],
        description: "S. haematobium infection from freshwater contact.",
        keyFeatures: "Painless terminal hematuria, eosinophilia.",
        investigations: "Urine microscopy for ova, serology.",
        redFlags: "Bladder cancer (chronic), obstructive uropathy.", durations: ["chronic"], severities: ["mild","moderate"] },
    ],
  },
  {
    id: "obgyn", nameEn: "Gynecology & Obstetrics", nameFr: "Gynécologie & Obstétrique",
    symptoms: ["pelvic_pain","vaginal_bleeding","vaginal_discharge","missed_period","fever","nausea","dysuria","abdominal_pain"],
    diseases: [
      { name: "Ectopic Pregnancy", symptoms: ["pelvic_pain","vaginal_bleeding","missed_period","abdominal_pain"],
        description: "Implantation outside uterine cavity.",
        keyFeatures: "Amenorrhea, unilateral pelvic pain, shoulder tip pain if rupture.",
        investigations: "Urine β-hCG, transvaginal US, serial β-hCG.",
        redFlags: "Hypovolemic shock from rupture.", durations: ["acute"], severities: ["severe"] },
      { name: "Pelvic Inflammatory Disease", symptoms: ["pelvic_pain","vaginal_discharge","fever","abdominal_pain"],
        description: "Ascending genital tract infection.",
        keyFeatures: "Cervical motion tenderness, fever, discharge.",
        investigations: "Swabs (GC/CT), pelvic US, β-hCG.",
        redFlags: "Tubo-ovarian abscess, infertility.", durations: ["acute","subacute"], severities: ["moderate"] },
      { name: "Threatened Miscarriage", symptoms: ["vaginal_bleeding","pelvic_pain","missed_period"],
        description: "Bleeding in early pregnancy with closed cervix.",
        keyFeatures: "Light bleeding, viable pregnancy on US.",
        investigations: "β-hCG, US.",
        redFlags: "Heavy bleeding, hemodynamic instability.", durations: ["acute"], severities: ["mild","moderate"] },
      { name: "Bacterial Vaginosis", symptoms: ["vaginal_discharge"],
        description: "Imbalance of vaginal flora.",
        keyFeatures: "Thin grey discharge, fishy odor, no itch.",
        investigations: "Whiff test, clue cells, pH >4.5.",
        redFlags: "Pregnancy complications (preterm labor).", durations: ["chronic"], severities: ["mild"] },
      { name: "Pre-eclampsia", symptoms: ["headache","leg_swelling","abdominal_pain","visual_change"],
        description: "Pregnancy hypertension with proteinuria after 20 weeks.",
        keyFeatures: "BP ≥140/90, proteinuria, edema.",
        investigations: "BP, urinalysis, LFTs, platelets, urate.",
        redFlags: "Eclampsia, HELLP, abruption.", durations: ["subacute"], severities: ["severe"] },
      { name: "Candidiasis (vulvovaginal)", symptoms: ["vaginal_discharge","pruritus","dysuria"],
        description: "Candida overgrowth.",
        keyFeatures: "Thick white 'cottage cheese' discharge, intense itch.",
        investigations: "KOH wet mount.",
        redFlags: "Recurrent → check for diabetes/immunosuppression.", durations: ["acute"], severities: ["mild"] },
    ],
  },
  {
    id: "peds", nameEn: "Pediatrics", nameFr: "Pédiatrie",
    symptoms: ["fever","cough","diarrhea","vomiting","rash","poor_feeding","irritability","seizure","dyspnea"],
    diseases: [
      { name: "Pediatric Malaria", symptoms: ["fever","vomiting","poor_feeding","irritability","seizure"],
        description: "P. falciparum infection in children — leading cause of mortality.",
        keyFeatures: "Fever, lethargy, splenomegaly, anemia.",
        investigations: "RDT, blood smear, glucose, Hb.",
        redFlags: "Cerebral malaria, severe anemia, hypoglycemia.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Acute Diarrheal Disease", symptoms: ["diarrhea","vomiting","poor_feeding","fever"],
        description: "Common cause of pediatric dehydration.",
        keyFeatures: "Loose stools, sunken eyes, reduced skin turgor.",
        investigations: "Clinical, electrolytes if severe.",
        redFlags: "Severe dehydration, shock.", durations: ["acute"], severities: ["mild","moderate","severe"] },
      { name: "Pneumonia (child)", symptoms: ["cough","fever","dyspnea","poor_feeding"],
        description: "Lower respiratory infection — top cause of under-5 mortality.",
        keyFeatures: "Tachypnea, chest indrawing, grunting.",
        investigations: "RR count, SpO2, CXR.",
        redFlags: "Hypoxia, central cyanosis, inability to feed.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Measles", symptoms: ["fever","rash","cough"],
        description: "Highly contagious paramyxovirus.",
        keyFeatures: "Koplik spots, maculopapular rash spreading cephalocaudally.",
        investigations: "Clinical, IgM serology.",
        redFlags: "Pneumonia, encephalitis, blindness.", durations: ["acute"], severities: ["moderate"] },
      { name: "Otitis Media (child)", symptoms: ["fever","irritability","poor_feeding"],
        description: "Middle ear infection in young children.",
        keyFeatures: "Ear tugging, crying, bulging TM.",
        investigations: "Otoscopy.",
        redFlags: "Mastoiditis.", durations: ["acute"], severities: ["mild"] },
      { name: "Febrile Seizure", symptoms: ["seizure","fever","irritability"],
        description: "Generalized seizure with fever in 6 mo–5 y.",
        keyFeatures: "Brief tonic-clonic, post-ictal sleep, normal exam after.",
        investigations: "Look for source; LP if meningitis suspected.",
        redFlags: "Focal/prolonged → atypical, evaluate for meningitis.", durations: ["acute"], severities: ["mild","moderate"] },
    ],
  },
  {
    id: "dental", nameEn: "Dental & Oral Health", nameFr: "Dentaire & Santé bucco-dentaire",
    symptoms: ["tooth_pain","gum_bleeding","oral_swelling","oral_ulcer","jaw_pain","sensitivity","halitosis","fever","trauma"],
    diseases: [
      { name: "Dental Caries", symptoms: ["tooth_pain","sensitivity"],
        description: "Bacterial demineralization of enamel/dentine.",
        keyFeatures: "Cold/sweet sensitivity, visible cavitation.",
        investigations: "Clinical, bitewing X-rays.",
        redFlags: "Pulpal involvement → pulpitis.", durations: ["chronic"], severities: ["mild","moderate"] },
      { name: "Pulpitis", symptoms: ["tooth_pain","sensitivity"],
        description: "Inflammation of dental pulp.",
        keyFeatures: "Sharp/throbbing pain, lingering after stimulus (irreversible).",
        investigations: "Pulp testing, periapical X-ray.",
        redFlags: "Spread to apical tissues.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Periapical Abscess", symptoms: ["tooth_pain","oral_swelling","fever","jaw_pain"],
        description: "Localized pus collection at root apex.",
        keyFeatures: "Severe throbbing, tender to percussion, swelling.",
        investigations: "Periapical X-ray, clinical exam.",
        redFlags: "Ludwig's angina, cavernous sinus thrombosis.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Gingivitis", symptoms: ["gum_bleeding","halitosis"],
        description: "Plaque-induced gingival inflammation, reversible.",
        keyFeatures: "Red swollen gums bleeding on brushing.",
        investigations: "Clinical, plaque index.",
        redFlags: "Progression to periodontitis.", durations: ["chronic"], severities: ["mild"] },
      { name: "Periodontitis", symptoms: ["gum_bleeding","halitosis","tooth_pain"],
        description: "Destruction of periodontal attachment.",
        keyFeatures: "Pocket depth >3mm, mobility, recession.",
        investigations: "Periodontal probing, X-rays.",
        redFlags: "Tooth loss, systemic disease links (diabetes, CVD).", durations: ["chronic"], severities: ["moderate"] },
      { name: "Oral Candidiasis", symptoms: ["oral_ulcer","oral_swelling"],
        description: "Candida albicans overgrowth.",
        keyFeatures: "White plaques wipe off leaving erythema.",
        investigations: "Clinical, KOH smear.",
        redFlags: "Suspect HIV/immunosuppression.", durations: ["subacute"], severities: ["mild","moderate"] },
      { name: "Aphthous Ulcer", symptoms: ["oral_ulcer"],
        description: "Recurrent benign mucosal ulcer.",
        keyFeatures: "Round/oval ulcer with yellow base, halo.",
        investigations: "Clinical.",
        redFlags: "Persistent >3 weeks → biopsy for malignancy.", durations: ["acute"], severities: ["mild"] },
      { name: "Dental Trauma", symptoms: ["tooth_pain","trauma","oral_swelling","jaw_pain"],
        description: "Injury to tooth or surrounding structures.",
        keyFeatures: "Fracture/avulsion/luxation post-impact.",
        investigations: "Clinical, periapical X-ray, CBCT if jaw fracture.",
        redFlags: "Avulsed permanent tooth — replant within 30 min.", durations: ["acute"], severities: ["moderate","severe"] },
    ],
  },
  {
    id: "endo", nameEn: "Endocrine & Metabolic", nameFr: "Endocrinien & Métabolique",
    symptoms: ["fatigue","weight_loss","weight_gain","polyuria","polydipsia","heat_intolerance","cold_intolerance","palpitations","tremor"],
    diseases: [
      { name: "Type 2 Diabetes Mellitus", symptoms: ["polyuria","polydipsia","fatigue","weight_loss"],
        description: "Insulin resistance with hyperglycemia.",
        keyFeatures: "Polyuria/polydipsia, blurred vision, recurrent infections.",
        investigations: "Fasting glucose, HbA1c, urinalysis.",
        redFlags: "DKA, HHS, severe infections.", durations: ["chronic"], severities: ["mild","moderate","severe"] },
      { name: "Diabetic Ketoacidosis", symptoms: ["polyuria","polydipsia","fatigue","nausea","vomiting","abdominal_pain"],
        description: "Acute insulin deficiency with ketosis.",
        keyFeatures: "Kussmaul breathing, fruity breath, dehydration.",
        investigations: "Glucose, ketones, ABG, electrolytes.",
        redFlags: "Coma, severe acidosis, hypokalemia.", durations: ["acute"], severities: ["severe"] },
      { name: "Hyperthyroidism (Graves)", symptoms: ["heat_intolerance","palpitations","weight_loss","tremor","fatigue"],
        description: "Excess thyroid hormone production.",
        keyFeatures: "Goiter, exophthalmos, fine tremor.",
        investigations: "TSH ↓, free T4 ↑, TRAb.",
        redFlags: "Thyroid storm, AF.", durations: ["chronic"], severities: ["moderate"] },
      { name: "Hypothyroidism", symptoms: ["cold_intolerance","weight_gain","fatigue"],
        description: "Underactive thyroid (often Hashimoto).",
        keyFeatures: "Dry skin, bradycardia, constipation.",
        investigations: "TSH ↑, free T4 ↓.",
        redFlags: "Myxedema coma.", durations: ["chronic"], severities: ["mild","moderate"] },
      { name: "Hypoglycemia", symptoms: ["fatigue","tremor","palpitations"],
        description: "Plasma glucose <3.9 mmol/L.",
        keyFeatures: "Sweating, hunger, confusion, autonomic signs.",
        investigations: "Capillary glucose.",
        redFlags: "Coma, seizures.", durations: ["acute"], severities: ["moderate","severe"] },
      { name: "Adrenal Insufficiency", symptoms: ["fatigue","weight_loss","abdominal_pain"],
        description: "Cortisol deficiency (Addison or secondary).",
        keyFeatures: "Hyperpigmentation, hypotension, salt craving.",
        investigations: "Morning cortisol, ACTH stim test, electrolytes.",
        redFlags: "Adrenal crisis — shock.", durations: ["chronic"], severities: ["moderate","severe"] },
    ],
  },
  {
    id: "psych", nameEn: "Psychiatry & Mental Health", nameFr: "Psychiatrie & Santé mentale",
    symptoms: ["low_mood","anxiety","insomnia","appetite_change","fatigue","hallucinations","suicidal_ideation","substance_use","palpitations"],
    diseases: [
      { name: "Major Depressive Disorder", symptoms: ["low_mood","insomnia","appetite_change","fatigue","suicidal_ideation"],
        description: "Persistent low mood with anhedonia ≥2 weeks.",
        keyFeatures: "Anhedonia, guilt, low energy, sleep change.",
        investigations: "PHQ-9, rule out hypothyroid/anemia.",
        redFlags: "Active suicidal plan, psychotic features.", durations: ["chronic"], severities: ["mild","moderate","severe"] },
      { name: "Generalized Anxiety Disorder", symptoms: ["anxiety","insomnia","fatigue","palpitations"],
        description: "Excessive worry on most days for ≥6 months.",
        keyFeatures: "Restlessness, muscle tension, irritability.",
        investigations: "GAD-7, exclude hyperthyroid, caffeine.",
        redFlags: "Panic with chest pain → exclude cardiac.", durations: ["chronic"], severities: ["mild","moderate"] },
      { name: "Panic Disorder", symptoms: ["anxiety","palpitations","insomnia"],
        description: "Recurrent unexpected panic attacks.",
        keyFeatures: "Sudden fear, palpitations, dyspnea, depersonalization.",
        investigations: "Clinical; rule out cardiac/thyroid.",
        redFlags: "Coexisting suicidal ideation.", durations: ["chronic"], severities: ["moderate"] },
      { name: "Schizophrenia", symptoms: ["hallucinations","insomnia","low_mood"],
        description: "Psychotic disorder with positive and negative symptoms.",
        keyFeatures: "Auditory hallucinations, delusions, social withdrawal.",
        investigations: "Clinical, exclude substance/organic causes.",
        redFlags: "Command hallucinations, violence/suicide risk.", durations: ["chronic"], severities: ["moderate","severe"] },
      { name: "Substance Use Disorder", symptoms: ["substance_use","insomnia","low_mood","anxiety"],
        description: "Problematic use causing impairment.",
        keyFeatures: "Tolerance, withdrawal, loss of control.",
        investigations: "Toxicology, LFTs, CAGE/AUDIT.",
        redFlags: "Withdrawal seizures, overdose.", durations: ["chronic"], severities: ["moderate","severe"] },
      { name: "Acute Stress Reaction", symptoms: ["anxiety","insomnia","low_mood"],
        description: "Transient response to severe stressor.",
        keyFeatures: "Hyperarousal, intrusive thoughts <1 month.",
        investigations: "Clinical.",
        redFlags: "Persistent >1 month → PTSD.", durations: ["acute"], severities: ["mild","moderate"] },
    ],
  },
  {
    id: "ophth", nameEn: "Ophthalmology", nameFr: "Ophtalmologie",
    symptoms: ["eye_pain","red_eye","visual_change","photophobia","discharge","itching","headache"],
    diseases: [
      { name: "Conjunctivitis (bacterial)", symptoms: ["red_eye","discharge","eye_pain"],
        description: "Bacterial conjunctival infection.",
        keyFeatures: "Purulent discharge, eyes 'glued' shut.",
        investigations: "Clinical, swab if severe.",
        redFlags: "Hyperacute (gonococcal) → emergency.", durations: ["acute"], severities: ["mild"] },
      { name: "Conjunctivitis (viral)", symptoms: ["red_eye","discharge","itching"],
        description: "Adenoviral conjunctivitis, highly contagious.",
        keyFeatures: "Watery discharge, preauricular node.",
        investigations: "Clinical.",
        redFlags: "Keratitis.", durations: ["acute"], severities: ["mild"] },
      { name: "Acute Angle-Closure Glaucoma", symptoms: ["eye_pain","red_eye","visual_change","headache","photophobia"],
        description: "Sudden rise in intraocular pressure.",
        keyFeatures: "Severe pain, halos around lights, fixed mid-dilated pupil.",
        investigations: "IOP measurement (>30 mmHg), gonioscopy.",
        redFlags: "Permanent vision loss without urgent treatment.", durations: ["acute"], severities: ["severe"] },
      { name: "Corneal Ulcer / Keratitis", symptoms: ["eye_pain","red_eye","photophobia","visual_change","discharge"],
        description: "Corneal infection, often bacterial or fungal.",
        keyFeatures: "White infiltrate on cornea, fluorescein uptake.",
        investigations: "Slit lamp, corneal scrape.",
        redFlags: "Perforation, endophthalmitis.", durations: ["acute"], severities: ["severe"] },
      { name: "Allergic Conjunctivitis", symptoms: ["itching","red_eye","discharge"],
        description: "IgE-mediated conjunctival inflammation.",
        keyFeatures: "Bilateral itching, watery, atopic history.",
        investigations: "Clinical.",
        redFlags: "Vernal keratoconjunctivitis in children.", durations: ["chronic"], severities: ["mild"] },
      { name: "Cataract", symptoms: ["visual_change"],
        description: "Lens opacification, age-related most common.",
        keyFeatures: "Gradual painless visual loss, glare.",
        investigations: "Slit lamp.",
        redFlags: "Mature cataract → phacolytic glaucoma.", durations: ["chronic"], severities: ["mild","moderate"] },
    ],
  },
];

export interface RankedDiagnosis extends Disease {
  score: number;
  confidence: Confidence;
  matchedSymptoms: string[];
}

export function rankDiagnoses(
  system: BodySystem,
  selectedSymptoms: string[],
  duration: "acute" | "subacute" | "chronic",
  severity: "mild" | "moderate" | "severe",
): RankedDiagnosis[] {
  const sel = new Set(selectedSymptoms);
  const ranked = system.diseases.map(d => {
    const matched = d.symptoms.filter(s => sel.has(s));
    let score = matched.length * 10;
    // bonus if proportion of disease symptoms matched is high
    if (d.symptoms.length) score += (matched.length / d.symptoms.length) * 5;
    if (d.durations && d.durations.includes(duration)) score += 4;
    if (d.severities && d.severities.includes(severity)) score += 3;
    return { ...d, score, matchedSymptoms: matched } as RankedDiagnosis;
  });

  const filtered = ranked.filter(d => d.matchedSymptoms.length > 0);
  filtered.sort((a, b) => b.score - a.score);

  // Confidence band based on score quartiles
  const top = filtered[0]?.score || 1;
  for (const d of filtered) {
    const ratio = d.score / top;
    d.confidence = ratio >= 0.75 ? "high" : ratio >= 0.5 ? "medium" : "low";
  }

  // Min 3 (if available), max 8
  return filtered.slice(0, Math.max(3, Math.min(8, filtered.length)));
}

/** Symptom display labels (EN/FR). Falls back to humanized key. */
export const SYMPTOM_LABELS: Record<string, { en: string; fr: string }> = {
  fever: { en: "Fever", fr: "Fièvre" },
  chills: { en: "Chills", fr: "Frissons" },
  sweats: { en: "Sweats", fr: "Sueurs" },
  headache: { en: "Headache", fr: "Céphalée" },
  fatigue: { en: "Fatigue", fr: "Fatigue" },
  myalgia: { en: "Muscle aches", fr: "Myalgies" },
  nausea: { en: "Nausea", fr: "Nausée" },
  vomiting: { en: "Vomiting", fr: "Vomissements" },
  diarrhea: { en: "Diarrhea", fr: "Diarrhée" },
  abdominal_pain: { en: "Abdominal pain", fr: "Douleur abdominale" },
  jaundice: { en: "Jaundice", fr: "Ictère" },
  rash: { en: "Rash", fr: "Éruption" },
  weight_loss: { en: "Weight loss", fr: "Perte de poids" },
  weight_gain: { en: "Weight gain", fr: "Prise de poids" },
  lymphadenopathy: { en: "Swollen lymph nodes", fr: "Adénopathies" },
  cough: { en: "Cough", fr: "Toux" },
  sputum: { en: "Sputum", fr: "Expectorations" },
  hemoptysis: { en: "Coughing blood", fr: "Hémoptysie" },
  dyspnea: { en: "Shortness of breath", fr: "Dyspnée" },
  wheeze: { en: "Wheeze", fr: "Sifflement" },
  chest_pain: { en: "Chest pain", fr: "Douleur thoracique" },
  night_sweats: { en: "Night sweats", fr: "Sueurs nocturnes" },
  palpitations: { en: "Palpitations", fr: "Palpitations" },
  syncope: { en: "Fainting", fr: "Syncope" },
  leg_swelling: { en: "Leg swelling", fr: "Œdème des jambes" },
  orthopnea: { en: "Orthopnea", fr: "Orthopnée" },
  constipation: { en: "Constipation", fr: "Constipation" },
  hematemesis: { en: "Vomiting blood", fr: "Hématémèse" },
  melena: { en: "Black stools", fr: "Méléna" },
  seizure: { en: "Seizure", fr: "Convulsion" },
  weakness: { en: "Weakness", fr: "Faiblesse" },
  numbness: { en: "Numbness", fr: "Engourdissement" },
  dizziness: { en: "Dizziness", fr: "Vertiges" },
  altered_consciousness: { en: "Altered consciousness", fr: "Conscience altérée" },
  visual_change: { en: "Visual change", fr: "Trouble visuel" },
  neck_stiffness: { en: "Neck stiffness", fr: "Raideur de nuque" },
  joint_pain: { en: "Joint pain", fr: "Arthralgie" },
  joint_swelling: { en: "Joint swelling", fr: "Gonflement articulaire" },
  back_pain: { en: "Back pain", fr: "Lombalgie" },
  muscle_weakness: { en: "Muscle weakness", fr: "Faiblesse musculaire" },
  stiffness: { en: "Stiffness", fr: "Raideur" },
  trauma: { en: "Trauma", fr: "Traumatisme" },
  pruritus: { en: "Itching", fr: "Prurit" },
  skin_lesion: { en: "Skin lesion", fr: "Lésion cutanée" },
  blisters: { en: "Blisters", fr: "Cloques" },
  scaling: { en: "Scaling", fr: "Desquamation" },
  skin_pain: { en: "Skin pain", fr: "Douleur cutanée" },
  ulcer: { en: "Ulcer", fr: "Ulcère" },
  ear_pain: { en: "Ear pain", fr: "Otalgie" },
  sore_throat: { en: "Sore throat", fr: "Mal de gorge" },
  nasal_congestion: { en: "Nasal congestion", fr: "Congestion nasale" },
  hoarseness: { en: "Hoarseness", fr: "Enrouement" },
  hearing_loss: { en: "Hearing loss", fr: "Perte d'audition" },
  facial_pain: { en: "Facial pain", fr: "Douleur faciale" },
  dysuria: { en: "Painful urination", fr: "Dysurie" },
  frequency: { en: "Urinary frequency", fr: "Pollakiurie" },
  hematuria: { en: "Blood in urine", fr: "Hématurie" },
  flank_pain: { en: "Flank pain", fr: "Douleur lombaire" },
  urinary_retention: { en: "Urinary retention", fr: "Rétention urinaire" },
  oliguria: { en: "Reduced urine output", fr: "Oligurie" },
  pelvic_pain: { en: "Pelvic pain", fr: "Douleur pelvienne" },
  vaginal_bleeding: { en: "Vaginal bleeding", fr: "Saignement vaginal" },
  vaginal_discharge: { en: "Vaginal discharge", fr: "Pertes vaginales" },
  missed_period: { en: "Missed period", fr: "Aménorrhée" },
  poor_feeding: { en: "Poor feeding", fr: "Mauvaise alimentation" },
  irritability: { en: "Irritability", fr: "Irritabilité" },
  tooth_pain: { en: "Tooth pain", fr: "Douleur dentaire" },
  gum_bleeding: { en: "Gum bleeding", fr: "Saignement gingival" },
  oral_swelling: { en: "Oral swelling", fr: "Gonflement buccal" },
  oral_ulcer: { en: "Oral ulcer", fr: "Ulcère buccal" },
  jaw_pain: { en: "Jaw pain", fr: "Douleur mâchoire" },
  sensitivity: { en: "Tooth sensitivity", fr: "Sensibilité dentaire" },
  halitosis: { en: "Bad breath", fr: "Halitose" },
  polyuria: { en: "Increased urination", fr: "Polyurie" },
  polydipsia: { en: "Increased thirst", fr: "Polydipsie" },
  heat_intolerance: { en: "Heat intolerance", fr: "Intolérance à la chaleur" },
  cold_intolerance: { en: "Cold intolerance", fr: "Intolérance au froid" },
  tremor: { en: "Tremor", fr: "Tremblement" },
  appetite_change: { en: "Appetite change", fr: "Changement d'appétit" },
  low_mood: { en: "Low mood", fr: "Humeur dépressive" },
  anxiety: { en: "Anxiety", fr: "Anxiété" },
  insomnia: { en: "Insomnia", fr: "Insomnie" },
  hallucinations: { en: "Hallucinations", fr: "Hallucinations" },
  suicidal_ideation: { en: "Suicidal thoughts", fr: "Idées suicidaires" },
  substance_use: { en: "Substance use", fr: "Consommation de substances" },
  eye_pain: { en: "Eye pain", fr: "Douleur oculaire" },
  red_eye: { en: "Red eye", fr: "Œil rouge" },
  photophobia: { en: "Photophobia", fr: "Photophobie" },
  discharge: { en: "Discharge", fr: "Écoulement" },
  itching: { en: "Itching", fr: "Démangeaison" },
};

export function symptomLabel(key: string, lang: "en" | "fr"): string {
  return SYMPTOM_LABELS[key]?.[lang] || key.replace(/_/g, " ");
}
