/**
 * Remote wipe via URL token.
 *
 * The "wipe secret" is generated by the admin and stored in localStorage on
 * every device that should be remotely-wipeable. Admin shares the URL
 * `https://app/?wipe=<secret>` manually (WhatsApp/SMS/email) to the doctor.
 * When the URL is opened on the target device, the app verifies the token
 * matches the locally-stored secret and erases all data.
 *
 * Fully offline — no server involved.
 */

const SECRET_KEY = "dl.wipe.secret.v1";

export function getWipeSecret(): string | null {
  return localStorage.getItem(SECRET_KEY);
}

export function setWipeSecret(secret: string): void {
  localStorage.setItem(SECRET_KEY, secret);
}

export function generateWipeSecret(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  return Array.from(bytes).map(b => b.toString(16).padStart(2, "0")).join("");
}

export function buildWipeUrl(secret: string): string {
  const u = new URL(window.location.href);
  u.search = "?wipe=" + secret;
  u.hash = "";
  return u.toString();
}

export async function performWipe(): Promise<void> {
  // Delete all IndexedDB databases we know about
  try {
    const { db } = await import("@/lib/db");
    await db.delete();
  } catch (e) {
    console.warn("[wipe] dexie delete failed", e);
  }
  // Best-effort: enumerate and drop everything
  try {
    if ((indexedDB as any).databases) {
      const dbs: any[] = await (indexedDB as any).databases();
      await Promise.all(dbs.map(d => d?.name && new Promise<void>(res => {
        const req = indexedDB.deleteDatabase(d.name);
        req.onsuccess = req.onerror = req.onblocked = () => res();
      })));
    }
  } catch {}
  try { localStorage.clear(); } catch {}
  try { sessionStorage.clear(); } catch {}
  try {
    if ("caches" in window) {
      const keys = await caches.keys();
      await Promise.all(keys.map(k => caches.delete(k)));
    }
  } catch {}
  try {
    if (navigator.serviceWorker) {
      const regs = await navigator.serviceWorker.getRegistrations();
      await Promise.all(regs.map(r => r.unregister()));
    }
  } catch {}
}

/** Check URL for ?wipe=<token>. If valid, wipe and show notice. */
export async function checkAndHandleWipeUrl(): Promise<boolean> {
  const params = new URLSearchParams(window.location.search);
  const token = params.get("wipe");
  if (!token) return false;
  const secret = getWipeSecret();
  if (secret && token === secret) {
    await performWipe();
    document.body.innerHTML = `
      <div style="min-height:100vh;display:flex;align-items:center;justify-content:center;
                  font-family:system-ui,sans-serif;padding:24px;text-align:center;background:#0b0b0b;color:#fff;">
        <div>
          <h1 style="font-size:22px;margin-bottom:12px;">Données effacées</h1>
          <p style="opacity:.8;margin-bottom:8px;">All local data has been erased.</p>
          <p style="opacity:.6;font-size:14px;">Redémarrez l'application — Restart the app.</p>
        </div>
      </div>`;
    return true;
  }
  return false;
}
